services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: joey
      POSTGRES_PASSWORD: sweep
      POSTGRES_DB: sweepmaps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./app:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

volumes:
  pgdata:
