version: '3.8'

services:
  postgres:
    build: .
    container_name: sweepmaps-db
    environment:
      POSTGRES_USER: joey
      POSTGRES_PASSWORD: sweep
      POSTGRES_DB: sweepmaps
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: